name: Test

on:
  workflow_dispatch:

jobs:
  do-something:
    runs-on: ubuntu-latest

    steps:
      - name: echo user
        run: echo $USER

      - name: sudo ls
        run: sudo ls /home
        
      - name: list users
        run: cat /etc/passwd
